### ISSUE TITLE
Create "FEC Dashboard" using "Naas Dashboard - Financial Consolidation" template

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/FEC-engine#1]
We want to reproduce the dashboard generated in Power BI/Looker using Plotly, from a template we can customize # Naas Dashboard - Financial Consolidation

Here is the current dashboard associated with the project :
<img width="1579" alt="Screenshot 2023-05-23 at 15 17 35" src="https://github.com/jupyter-naas/FEC-engine/assets/21052349/5aaeab34-03cf-4c63-b833-ae51d765b58e">
<img width="1584" alt="Screenshot 2023-05-23 at 15 17 40" src="https://github.com/jupyter-naas/FEC-engine/assets/21052349/2776f778-0c82-4406-9118-5665f6eeb23a">

Here is the current template: 
<img width="1723" alt="Screenshot 2023-05-23 at 15 19 15" src="https://github.com/jupyter-naas/FEC-engine/assets/21052349/5ad1b260-dbd2-4698-b8a9-34be070d9430">

What we to do is: 

→ on Navbar: 
- change logo to "n" naas logo 
- rename title to "FEC engine" 
- change navbar color to black 
- nothing to change on dropdown scenario and entity (we will change the data later)

→ on KPI section 
- maintain 6 boxes : nothing to do 
- change the name of the boxes 
- add variation in main KPI with sentiment (red/green) 
- add value below variation
- change background color or each box to light white: HEX code #fbfbfb

→ on Charts section 
- remove scorecard on the right side 
- split screen in 2 rows and 2 columns of equal size 
- create linechart in position 1:1 "EVOLUTION CHIFFRE D'AFFAIRES" → https://github.com/jupyter-naas/awesome-notebooks/blob/master/FEC/FEC_Visualiser_Comparer_Ventes_Line_Chart.ipynb
- reuse "REVENUE" in position 1:2 "POSITION DE TRESORERIE" → https://github.com/jupyter-naas/awesome-notebooks/blob/master/FEC/FEC_Visualiser_Tr%C3%A9sorerie_Barline_Chart.ipynb
- create horizontal barchart in position 2:1 "CHARGES" → @FlorentLvr template to be created
- create treemap in position 2:2 "BILAN" → there is a template for that: https://github.com/jupyter-naas/awesome-notebooks/blob/master/FEC/FEC_Visualiser_Bilan_Treemap.ipynb

**Comment by alexandrestevenspbix** [comment]
Add sous-title in chart carrd @FlorentLvr

**Comment by FlorentLvr** [comment]
@alexandrestevenspbix 
- Integrate all charts in Dashboard
- Finetuning: add a new row below title, color + conditional formating on KPIS

**Comment by FlorentLvr** [comment]
To do:
- GLOBAL
Passer toutes les données en K€ (Description des graphiques à modifier)

- KPIs:
Chiffre en valeur absolue en premier
Variation en second avec couleur

- EVOLUTION DU CA: 
Description: N vs N-1, mensuel (en euros)
Ajouter la légende en bas centrée
Remplacer le nom des mois par le numéro du mois

- POSITION TRESORERIE: 
Ajouter la légende en bas centrée
Remplacer le 2022-01 par le numéro du mois "01"

- CHARGES
Ajouter mardin_pad
Modifier les couleurs des barres (iso courbe)
Ajouter double barres (@FlorentLvr)

**Comment by alexandrestevenspbix** [comment]
@FlorentLvr @jravenel Je trouve ça plus lisible de la placer en haut
Pour moi le user flow c'est :
1. Lecture du titre
2. Lecture du sous-titre
3. Lecture de la légende
4. Analyse du graphique

Sans assimilation de la légende avant, difficle de comprendre le graphique
![image](https://github.com/jupyter-naas/FEC-engine/assets/84854803/b16aeb10-6b4d-4891-a350-58055827896b)
