### ISSUE TITLE
Add AI analysis on graph

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/FEC-engine#14]
Generate AI analysis on each graph

**Comment by jravenel** [comment]
@FlorentLvr here are my comment to close this, I create placeholders we can use to be more accurate and also keep the comment under a certain number of lines
[FEC Dashboard.pdf](https://github.com/jupyter-naas/FEC-engine/files/11669140/FEC.Dashboard.pdf)
. What do you think?
